image: 'haydenbr/new-years-client:3.0.0-dev'
clone:
  depth: 1
pipelines:
  branches:
    dev:
      - step:
          script:
            - source ./scripts/bitbucket-dev-env.sh
            - ./scripts/bitbucket-build.sh
    test:
      - step:
          script:
            - source ./scripts/bitbucket-test-env.sh
            - ./scripts/bitbucket-build.sh
    master:
      - step:
          script:
            - source ./scripts/bitbucket-prod-env.sh
            - ./scripts/bitbucket-build.sh
